"""
Run Phase 2 on the provided patent claims.
"""

import sys
import os
import json

# Add paths - go up two levels to patent_cpc_fastapi
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from cpc_classification.search_cpc import CPCClassifier

# The claims text
claims_text = """Method for evaluating a function implemented by an embedded system of a vehicle (10), said method being implemented by at least one processor and comprising the following steps: - receiving (41) first data representative of a request to display a second graphical content of a human-machine interface, called MMI; - checking (42) the display of said second graphical content of said MMI on a touch-interface display screen, called touch screen, following the reception of said first data, said second graphical content being representative of a form for collecting second data representative of a result of a test of said function; - transmitting (43) said second data to a remote device (101) via a wireless connection; - aggregating (44), by a large-scale language model, called LLM, said second data with third data representative of results of testing of said function implemented by a set of onboard systems of a set of other vehicles; - evaluating (45) said function by said LLM as a function of fourth data representative of a result of the aggregation; and - receiving (46) correction instructions of said function, the correction instructions being a function of a result of said evaluation (45) of said function by said LLM.

The method according to claim 1, wherein said first data are generated by a touch press on a graphic object displayed on said touch screen in a first determined graphic content of the MMI.

Method according to Claim 1 or 2, for which, a set of parameters being associated with said function, said correction instructions comprise a correction of at least one part of said set of parameters, said correction being obtained by refining said set of parameters as a function of said fourth data according to a reinforcement learning method.

Method according to one of claims 1 to 3, wherein said second data comprise: - data representative of text describing the result of the test; and/or - data representative of an image illustrating the result of the test; and/or - data representative of a score of the function as a result of the test.

The method of one of claims 1 to 4, wherein said LLM implements enhanced recovery generation to aggregate said second and third data.

The method according to one of claims 1 to 5, further comprising a step of identifying said vehicle (10)."""

print("=" * 70)
print("Running Phase 1 + Phase 2 Pipeline")
print("=" * 70)

try:
    classifier = CPCClassifier(model_name="phi4-reasoning:plus", knowledge_graph=None)
    result = classifier.classify(text=claims_text, claims=claims_text)

    print("\n" + "=" * 70)
    print("PHASE 1 OUTPUT (Key Fields)")
    print("=" * 70)
    phase1 = result.get("phase1", {})
    print(f"Technical Object: {phase1.get('technical_object', 'N/A')[:120]}...")
    print(f"Core Function: {phase1.get('core_function', 'N/A')}")
    print(f"System Context: {phase1.get('system_context', 'N/A')}")
    print(f"Classification Strategy: {phase1.get('classification_strategy', 'N/A')}")
    print(f"\nTop Terms:")
    terms = phase1.get("essential_terms", [])[:10]
    for t in terms:
        if isinstance(t, dict):
            print(f"  - {t.get('term', '')}: {t.get('importance', 0)}")
    print(f"\nClass Hypotheses:")
    for h in phase1.get("class_hypotheses", [])[:5]:
        if isinstance(h, dict):
            print(f"  - {h.get('class', '')}: {h.get('confidence', 0)}")

    print("\n" + "=" * 70)
    print("PHASE 2 OUTPUT")
    print("=" * 70)
    phase2 = result.get("phase2", {})
    print(f"Phase 2A Families: {phase2.get('phase2a_families', [])}")
    print(f"Phase 2A Source: {phase2.get('phase2a_source', 'N/A')}")
    print(f"Phase 2A Reasoning: {phase2.get('phase2a_reasoning', 'N/A')[:150]}...")
    print(f"Phase 2B Candidate Count: {phase2.get('phase2b_candidate_count', 0)}")
    print(f"Phase 2C Final Count: {phase2.get('phase2c_final_count', 0)}")
    print(f"Score Margin: {phase2.get('score_margin', 0)}")
    print(f"Confidence Level: {phase2.get('confidence_level', 'N/A')}")
    print(f"\nTop Codes:")
    for code in phase2.get("codes", [])[:7]:
        print(f"  - {code}")

    print("\n" + "=" * 70)
    print("PHASE 3 (Ranked with Scores)")
    print("=" * 70)
    for node in result.get("phase3", [])[:7]:
        print(f"  {node['symbol']} | {node['title'][:60]}... | Score: {node['score']}")

    print("\n" + "=" * 70)
    print("FINAL CPC CODES")
    print("=" * 70)
    for cpc in result.get("cpc", [])[:5]:
        print(f"  {cpc['code']} | Score: {cpc['score']}")

    if result.get("premier"):
        print(f"\nPremier Code: {result['premier']['symbol']}")
        print(f"Confidence: {result['premier']['confidence']}")

    # Save full result for inspection
    output_path = "phase2_output.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)
    print(f"\n[Saved full result to {output_path}]")

except Exception as e:
    print(f"Error: {e}")
    import traceback

    traceback.print_exc()
